#!/bin/sh

# this is where todo.md will be stored if the file doesn't exist locally
folder=$HOME

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
if [ -f todo.md ]; then
  "$dir/../bin/todo" "$@"
else
  (cd $folder && "$dir/../bin/todo" "$@")
fi
