#!/bin/sh

# this is where todo.md will be stored if the file doesn't exist locally
folder=~

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
if [ -f todo.md ]; then
  "$dir/../bin/todo" "$@"
else
  pushd $folder > /dev/null
  "$dir/../bin/todo" "$@"
  popd > /dev/null
fi
